services:
  db:
    image: mysql:8.0
    container_name: anigura_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "b0nny!"
      MYSQL_DATABASE: anigura_db
      MYSQL_USER: dannylm
      MYSQL_PASSWORD: "4321!"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: anigura_db_gui
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "b0nny!"
    depends_on:
      - db
    volumes:
      - ./.themes/blueberry:/var/www/html/themes/blueberry
  
  api:
    build: ./anigura_api
    container_name: anigura_api
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./anigura_api:/var/www/html
    depends_on:
      - db

  front:
    build: ./anigura
    container_name: anigura
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    ports:
      - "5173:5173"
    volumes:
      - ./anigura:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  db_data:
