# users.http
@baseUrl = http://localhost:8000
@contentType = application/json
@userId = 17
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzczNTM5NzkwLCJleHAiOjE3NzM1NDY5OTB9.dmbtYLf06oPVGR5w48UcDaGSoCkV--sKmM1Obop93Uc
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM1Mzk4MDQsImV4cCI6MTc3MzU0NzAwNH0.pZX-HJCSlMTDRbwFw6P6GJ7i0flw7OMZRoHIoKI_Nuo


## List users — admin
GET {{baseUrl}}/users
Accept: {{contentType}}
Authorization: Bearer {{adminToken}}

### Response
// {"status":"success","code":200,"msg":"Request success","data":{"info":{"total":3,"pages":1,"current":1,"next":null,"prev":null},"results":[{"id":1,"role":"admin","full_name":"Danny LM","email":"dannylm@anigura.mx","rfc":null,"created_at":"2026-02-23 09:05:14","updated_at":"2026-02-23 09:05:14"},{"id":2,"role":"user","full_name":"Ahley","email":"ashley@anigura.mx","rfc":null,"created_at":"2026-02-23 09:06:13","updated_at":"2026-02-23 09:06:13"},{"id":17,"role":"user","full_name":"Test User","email":"test1@anigura.mx","rfc":null,"created_at":"2026-03-15 01:03:00","updated_at":"2026-03-15 01:03:00"}]},"timestamp":"2026-03-15 01:59:03"}


## Get specific user — admin
GET {{baseUrl}}/users/{{userId}}
Accept: {{contentType}}
Authorization: Bearer {{adminToken}}

### Response
// {"status":"success","code":200,"msg":"Request success","data":{"id":17,"role":"user","full_name":"Test User","email":"test1@anigura.mx","rfc":null,"created_at":"2026-03-15 01:03:00","updated_at":"2026-03-15 01:03:00"},"timestamp":"2026-03-15 01:59:24"}


## Update user — admin
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
    "full_name": "Test User Updated"
}

### Response
// {"status":"success","code":200,"msg":"User updated","data":null,"timestamp":"2026-03-15 02:00:10"}
### Response (get updated user)
// {"status":"success","code":200,"msg":"Request success","data":{"id":17,"role":"user","full_name":"Test User Updated","email":"test1@anigura.mx","rfc":null,"created_at":"2026-03-15 01:03:00","updated_at":"2026-03-15 02:00:10"},"timestamp":"2026-03-15 02:00:51"}


## Delete user — admin
DELETE {{baseUrl}}/users/{{userId}}
Accept: {{contentType}}
Authorization: Bearer {{adminToken}}

### Response
// {"status":"success","code":200,"msg":"User deleted","data":null,"timestamp":"2026-03-15 02:08:38"}
### Response (x2)
// {"status":"error","code":404,"msg":"User not found","data":null,"timestamp":"2026-03-15 02:09:11"}
### Response (get deleted user)
// {"status":"error","code":404,"msg":"User not found","data":null,"timestamp":"2026-03-15 02:09:21"}


## Search user by email — any auth
POST {{baseUrl}}/users/search
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
    "email": "dannylm@anigura.mx"
}

### Response
// {"status":"success","code":200,"msg":"Request success","data":{"id":1,"role":"admin","full_name":"Danny LM","email":"dannylm@anigura.mx","rfc":null,"created_at":"2026-02-23 09:05:14"},"timestamp":"2026-03-15 02:09:43"}


## Search - Fail (not found)
POST {{baseUrl}}/users/search
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
    "email": "noexiste@anigura.mx"
}

### Response
// {"status":"error","code":404,"msg":"User with email noexiste@anigura.mx not found","data":null,"timestamp":"2026-03-15 02:09:57"}


## List users — Fail (user role)
GET {{baseUrl}}/users
Authorization: Bearer {{userToken}}

### Response
// {"status":"error","code":403,"msg":"Access denied. Required role: admin","data":null,"timestamp":"2026-03-15 02:10:06"}
