# addresses.http
@baseUrl = http://localhost:8000
@contentType = application/json
@addressId = 1
@userId = 1


### List addresses
GET {{baseUrl}}/addresses
Accept: {{contentType}}


### Create address
POST {{baseUrl}}/addresses
Content-Type: {{contentType}}

{
    "id_user": 1,
    "alias": "House",
    "street": "10 Unknown",
    "city": "Unknown City",
    "state": "Unknown State",
    "zip_code": "460-0001",
    "is_default": false
}


### Get specific address
GET {{baseUrl}}/addresses/{{addressId}}
Accept: {{contentType}}


### Update address (Partial)
PATCH  {{baseUrl}}/addresses/{{addressId}}
Content-Type: {{contentType}}

{
    "is_default": true
}


### Delete address
DELETE {{baseUrl}}/addresses/{{addressId}}
Accept: {{contentType}}


### Default user address
GET {{baseUrl}}/addresses/user/{{userId}}
Accept: {{contentType}}
