# cartItems.http
@baseUrl = http://localhost:8000
@contentType = application/json
@userId = 2
@productId = 11
@cartItemId = 2


### Get Ashley Cart
GET {{baseUrl}}/cart/{{userId}}
Accept: {{contentType}}


### Add 2 Frieren figures (id: 11)
POST {{baseUrl}}/cart/{{userId}}
Content-Type: {{contentType}}

{
    "id_product": 11,
    "quantity": 2
}


### Add Bocchi Manga Vol. 1 (id: 2) two times
POST {{baseUrl}}/cart/{{userId}}
Content-Type: {{contentType}}

{
    "id_product": 2,
    "quantity": 1
}


### Update item qty
PATCH {{baseUrl}}/cart/{{userId}}/{{cartItemId}}
Content-Type: {{contentType}}

{
    "quantity": 5
}


### Try to add more stock than the allowed
POST {{baseUrl}}/cart/{{userId}}
Content-Type: {{contentType}}

{
    "id_product": 11,
    "quantity": 15
}


### Remote cart item
DELETE {{baseUrl}}/cart/{{userId}}/1
