# franchises.http
@baseUrl = http://localhost:8000
@contentType = application/json
@franchiseId = 1


### List franchises
GET {{baseUrl}}/franchises
Accept: {{contentType}}


### Create franchise
POST {{baseUrl}}/franchises
Content-Type: {{contentType}}

{
    "name": "Frieren: Beyond Journey's End"
}

# "name" => "!null|max:255",
# "synopsis" => ""


### Get specific franchise
GET {{baseUrl}}/franchises/{{franchiseId}}
Accept: {{contentType}}


### Update franchise (Partial)
PATCH  {{baseUrl}}/franchises/{{franchiseId}}
Content-Type: {{contentType}}

{
    "synopsis": "After the hero's party defeats the Demon King, the elven mage Frieren continues living for centuries while her human companions age and die. Confronting the weight of time and loss, she embarks on a new journey to understand humanity and the people she failed to truly know."
}


### Delete franchise
DELETE {{baseUrl}}/franchises/{{franchiseId}}
Accept: {{contentType}}
