# series.http
@baseUrl = http://localhost:8000
@contentType = application/json


### List series
GET {{baseUrl}}/series
Accept: {{contentType}}


### Create serie
POST {{baseUrl}}/series
Content-Type: {{contentType}}

{
    "name": "The Rising of the Shield Hero",
    "work_type": "manga",
    "author": "sepa"
}


### Get specific serie
@serieId = 9
GET {{baseUrl}}/series/{{serieId}}
Accept: {{contentType}}


### Update serie (Partial)
PUT {{baseUrl}}/series/{{serieId}}
Content-Type: {{contentType}}

{
    "author": "Aneko Yusagi",
    "synopsis": "Naofumi Iwatani, an unordinary otaku, is summoned to another world to become the Shield Hero. After being betrayed, he must survive and protect the world from the Waves of Catastrophe."
}


### Delete serie
DELETE {{baseUrl}}/series/{{serieId}}
Accept: {{contentType}}
