# users.http
@baseUrl = http://localhost:8000
@contentType = application/json


### List users
GET {{baseUrl}}/users
Accept: {{contentType}}


### Create user
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
    "full_name": "Ashley",
    "email": "ashleylm@anigura.mx",
    "password": "Pass4321!"
}


### Get specific user
@userId = 1
GET {{baseUrl}}/users/{{userId}}
Accept: {{contentType}}


### Update user (Partial)
@userId = 1
PUT {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}

{
    "role": "admin"
}


### Delete user
@userId = 1
DELETE {{baseUrl}}/users/{{userId}}
Accept: {{contentType}}


### Search user by email
POST {{baseUrl}}/users/search
Content-Type: {{contentType}}

{
    "email": "dannylm@anigura.mx"
}

### Login - Success Case
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "dannylm@anigura.mx",
    "password": "Pass4321!"
}

### Login - Fail Case (wrong password)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "dannylm@anigura.mx",
    "password": "pas4321"
}
