# users.http
@baseUrl = http://localhost:8000
@contentType = application/json
@userId = 6


### List users
GET {{baseUrl}}/users
Accept: {{contentType}}


### Create user
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "full_name": "Danny LM",
    "email": "dannylm@anigura.mx",
    "password": "Pass4321!"
}

# "role" => "",
# "full_name" => "!null|max:255",
# "email" => "!null|email|max:150",
# "password" => "!null|min:8|max:255",
# "rfc" => "max:13",

# role enum = user, admin


### Get specific user
GET {{baseUrl}}/users/{{userId}}
Accept: {{contentType}}


### Update user (Partial)
PATCH  {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}

{
    "full_name": "Ashley 5",
    "email": "ashleyUpdate@anigura.mx",
    "password": "epa!!"
}


### Delete user
DELETE {{baseUrl}}/users/{{userId}}
Accept: {{contentType}}


### Search user by email
POST {{baseUrl}}/users/search
Content-Type: {{contentType}}

{
    "email": "dannylm@anigura.mx"
}


### Login - Success Case
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "dannylm@anigura.mx",
    "password": "Pass4321!"
}


### Login - Fail Case
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "danny@anigura.mx",
    "password": "pass4321!"
}
